# Generated by Django 5.0.2 on 2024-12-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileHub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='pdf_file',
            field=models.FileField(max_length=1000, upload_to='media/'),
        ),
    ]
