# Generated by Django 5.0.2 on 2025-01-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileHub', '0002_alter_fileupload_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='pdf_file',
            field=models.FileField(max_length=1000, upload_to=''),
        ),
    ]
