# Generated by Django 5.0.2 on 2025-01-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileHub', '0003_alter_fileupload_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw_Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_pdfs', models.FileField(max_length=1000, upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='FileUpload',
            new_name='Main_Storage',
        ),
    ]
