# Generated by Django 5.0.2 on 2025-01-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileHub', '0004_raw_storage_rename_fileupload_main_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usermail', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
